####################################################################
####################################################################
####################################################################
#██    ██ ██    ██ ██      ██ ███    ███  █████  ██ ████████ ███████
#██    ██ ██    ██ ██      ██ ████  ████ ██   ██ ██    ██    ██
#██    ██ ██    ██ ██      ██ ██ ████ ██ ███████ ██    ██    █████
#██  ██   ██  ██  ██      ██ ██  ██  ██ ██   ██ ██    ██    ██
#████     ████   ███████ ██ ██      ██ ██   ██ ██    ██    ███████
####################################################################
####################################################################
####################################################################

#This Plugin is from EliVB

#This is a Plugin like DonutSMP Teams, you can change all of the messages here.
#For more Premium Skripts or Plugins join our Discord: "https://discord.gg/V3fcWZrccj"

#permissions
#team.admin - allows all admin commands

#placeholders
#%team% - Team Name

sounds:
  click-sound: "UI_BUTTON_CLICK"
  plugin-reloaded: "ENTITY_PLAYER_LEVELUP"
  error-sound: "ENTITY_VILLAGER_NO"
  success-sound: "ENTITY_PLAYER_LEVELUP"
  teleport-cooldown: "BLOCK_NOTE_BLOCK_PLING"
  teleport-complete: "ENTITY_ENDERMAN_TELEPORT"
  teleport-cancel: "ENTITY_VILLAGER_NO"

team-home:
  enabled: true
  teleport-delay: 5
  teleport-distance: 0.3

mind-team-name-length: 3
max-team-name-length: 9

blocked-team-names:
  - "nigger"
  - "fuck"
