name: HLSMP-Teams
version: '1.0'
main: de.elivb.hlsmpTeams.Team
api-version: '1.21'
author: EliVB
description: Team plugin cho HLSMP Server
folia-supported: true
softdepend: [PlaceholderAPI]

commands:
  team:
    aliases: [teams]
  teamtoggle:
  teamchattoggle:

permissions:
  team.admin:
    default: op
  team.home.bypass:
    default: false
